version: 2.1

jobs:
  commit_stage:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - maven-repo-twentyone-{{ .Branch }}-{{ checksum "pom.xml" }}
            - maven-repo-twentyone-{{ .Branch }}-
            - maven-repo-twentyone-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-twentyone-{{ .Branch }}-{{ checksum "pom.xml" }}
      - run:
          name: Maven build & Sonar analysis
          command: mvn verify -B sonar:sonar -Dsonar.projectKey=ikhoury_twentyone -Dsonar.organization=ikhoury -Dsonar.host.url=https://sonarcloud.io
      - store_test_results:
          path: target/surefire-reports

workflows:
  main:
    jobs:
      - commit_stage:
          context: SonarCloud